networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: yashwanth24710/mongo:v1
    container_name: mongodb
  catalogue:
    image: yashwanth24710/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis: 
    image: redis
    container_name: redis
  user:
    image: yashwanth24710/user:v1
    container_name: user
    depends_on: 
    - mongodb
    - redis    
  cart:
    image: yashwanth24710/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: yashwanth24710/mysql:v1
    container_name: mysql
  shipping:
    image: yashwanth24710/shipping:v1
    container_name: shipping
    depends_on:
    - mysql         
  web:
    image: yashwanth24710/web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - mysql
    - payment
    - ratings
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: yashwanth24710/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  ratings:
    image: yashwanth24710/ratings:v1
    container_name: ratings 
    depends_on:
    - mysql   
